# This is a basic workflow to help you get started with Actions

name: Check Databases

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Install MySQL 5.7
        shell: bash
        run: |
          brew install mysql
          brew install mysql@5.7
          brew unlink mysql && brew link mysql@5.7
          echo 'export PATH="/usr/local/opt/mysql@5.7/bin:$PATH"' >> /Users/runner/.bash_profile
          bash
          mysql --version
          mysqldump --version
      # Runs a single command using the runners shell
      - name: Check MySQL schemas
        uses: ./
        with: 
          hostname1: ${{ secrets.HOSTNAME1 }}
          username1: ${{ secrets.USERNAME1 }}
          password1: ${{ secrets.PASSWORD1 }}
          database1: ${{ secrets.DATABASE1 }}
          hostname2: ${{ secrets.HOSTNAME2 }}
          username2: ${{ secrets.USERNAME2 }}
          password2: ${{ secrets.PASSWORD2 }}
          database2: ${{ secrets.DATABASE2 }}
